extends:
  - plugin:svelte/recommended
overrides:
  -
    files:
      - '**/*.svelte'
    parser: svelte-eslint-parser
    rules:
      brace-style: off
  -
    files:
      - '**/*.spec.js'
    rules:
      no-invalid-this: off
      no-new: off
