overrides:
  -
    files:
      - '**/*.svelte'
    processor: svelte3/svelte3
    rules:
      brace-style: off
  -
    files:
      - '**/*.spec.js'
    rules:
      no-invalid-this: off
      no-new: off
plugins:
  - svelte3
