extends:
  - plugin:svelte/recommended
overrides:
  -
    files:
      - '**/*.svelte'
    parser: svelte-eslint-parser
  -
    files:
      - '**/*.spec.js'
    rules:
      no-invalid-this: 'off'
      no-new: 'off'
rules:
  brace-style: 'off'
  no-invalid-this: 'off'
  no-process-env: 'off'
  no-tabs: 'off'
  unused-export-let: 'off' # `export let prop` in components
