urls:
  a: NUTS_HOME_URL
files:
  a: NUTS_DATABASE_DIR_0/nuts_spec.yaml
  b: NUTS_DATABASE_DIR_1/countries_by_year.yaml
  c/: NUTS_DATABASE_DIR_1/sourceText/*
  d/: NUTS_DATABASE_DIR_1/topojson/*
  e/: NUTS_DATABASE_DIR_2/topojson/*
scripts:
  - path: 01_getMetadata.js
  inputs:
    - files.a
    - urls.a
  outputs:
    - b
    - c/
  - path: 01_getShapes.js
  inputs:
    - files.a
    - urls.a
  outputs:
    - d/
  - path: 12_getCountriesTopojson.js
  inputs:
    - files.b
    - files.d/
  outputs:
    - e/
